version: 2.1
orbs:
  node: circleci/node@7.1.0
  aws-cli: circleci/aws-cli@5.3.4
workflows:
  full:
    jobs:
      - build:
          context: org-global

jobs:
  build:
    docker:
      - image: cimg/node:16.20.2
    steps:
      - checkout
      - aws-cli/setup
      - node/install-packages:
          cache-path: ~/project/node_modules
          pkg-manager: yarn
          override-ci-command: yarn install
      - run:
          name: Lint
          command: yarn lint
      - deploy:
          name: Deploy
          filters:
            branches:
              only:
                - master
                - staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bash ./deploy.sh
            fi
