version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.2.1
workflows:
  full:
    jobs:
      - build:
          context: org-global

jobs:
  build:
    docker:
      - image: cimg/node:20.5-browsers
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.14.0'
      - node/install-packages:
          cache-path: ~/project/node_modules
          pkg-manager: yarn
          override-ci-command: yarn install
          cache-version: v1
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Build
          command: yarn build:storybook
      - deploy:
          name: Deploy
          filters:
            branches:
              only:
                - master
                - staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bash ./deploy.sh
            fi
